CREATE TABLE MEMBER
(
    MEMBER_ID BIGINT AUTO_INCREMENT,
    ROLE      VARCHAR(10) NOT NULL,

    PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE LOGIN_INFO
(
    MEMBER_ID  BIGINT,
    EMAIL      VARCHAR(50) NOT NULL,
    PASSWORD   VARCHAR(100),
    LOGIN_TYPE VARCHAR(10) NOT NULL,
    GOOGLE_SUB VARCHAR(100),

    PRIMARY KEY (MEMBER_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT UK_EMAIL_LOGIN_TYPE UNIQUE (EMAIL, LOGIN_TYPE),
    CONSTRAINT UK_GOOGLE_SUB UNIQUE (GOOGLE_SUB)
);